# default to the python provider
# nixpacks for railway frontend deployment. Copy to nixpacks.toml and deploy with `railway up`
providers = ['python']

# set up some variables to minimize annoyance
[variables]
    NEXT_TELEMETRY_DISABLED = '1' # disable next telemetry
    NPM_CONFIG_UPDATE_NOTIFIER = 'false' # the update check is relatively useless in a production environment
    NPM_CONFIG_FUND = 'false' # the fund notification is also relatively useless in a production environment
    PIP_DISABLE_PIP_VERSION_CHECK = '1' # the update check is relatively useless in a production environment
    NIXPACKS_DEBIAN_PACKAGES = "libstdc++6,build-essential,gcc,g++,libc6-dev" # system dependencies for numpy/scientific libraries

# system dependencies setup phase
[phases.system]
    aptPkgs = ['libstdc++6', 'build-essential', 'gcc', 'g++', 'libc6-dev']

# install uv package manager
[phases.uv-install]
    dependsOn = ['system']
    cmds = ['pip install uv']

# install dependencies using uv and pyproject.toml
[phases.install]
    dependsOn = ['uv-install']
    cmds = ['uv sync --frozen']

# default setup phase
[phases.setup]
    dependsOn = ['install']
    nixPkgs = ['...', 'unzip', 'parallel'] # install unzip because reflex needs it, and install parallel to run the frontend and backend at the same time
    nixLibs = ['zlib']

# reflex init phase
[phases.init]
    dependsOn = ['setup'] # run after setup
    cmds = ['uv run reflex init --loglevel debug'] # re-initialize the app with the latest template using uv

# export frontend phase
[phases.export]
    dependsOn = ['init'] # run after init
    cmds = [
        'FRONTEND_DEPLOY_URL="${FRONTEND_DEPLOY_URL}"',
        'REFLEX_API_URL="${REFLEX_API_URL}"',
        'uv run reflex export --frontend-only --no-zip --loglevel debug'
    ]
    # export the frontend with debug logging

# install caddy phase
[phases.caddy]
    dependsOn = ['export']
    nixpkgsArchive = 'ced9bf9f7c303c7d4acc6c4a1bb44368c6baae3f' # https://github.com/NixOS/nixpkgs/commit/ced9bf9f7c303c7d4acc6c4a1bb44368c6baae3f (Caddy v2.7.5)
    nixPkgs = ['caddy'] # install caddy

# format the caddyfile
[phases.fmt]
    dependsOn = ['caddy'] # run after caddy
    cmds = ['caddy fmt --overwrite'] # format the caddyfile and overwrite changes

# start phase
[start]
    cmd = 'REFLEX_ACCESS_TOKEN="${REFLEX_ACCESS_TOKEN}" REFLEX_SHOW_BUILT_WITH_REFLEX=0 FRONTEND_DEPLOY_URL="${FRONTEND_DEPLOY_URL}" REFLEX_API_URL="${REFLEX_API_URL}" uv run reflex run --frontend-only --env ${REFLEX_ENV_MODE:-prod} && caddy run 2>&1'
    # run the frontend and caddy in parallel, this will fail fast if either service crashes allowing railway to restart the deployment