# Minimal nixpacks configuration for debugging
providers = ['python']

# minimal variables
[variables]
    NEXT_TELEMETRY_DISABLED = '1'
    PIP_DISABLE_PIP_VERSION_CHECK = '1'
    LD_LIBRARY_PATH = '/nix/store/*/lib'

# minimal setup phase
[phases.setup]
    nixPkgs = ['...', 'unzip', 'curl', 'gcc']
    nixLibs = ['zlib']

# install uv package manager - simplified
[phases.uv-install]
    dependsOn = ['setup']
    cmds = [
        'pip install uv',
        'which uv'
    ]

# install dependencies
[phases.install]
    dependsOn = ['uv-install']
    cmds = [
        'uv sync'
    ]

# reflex init
[phases.init]
    dependsOn = ['install']
    cmds = [
        'uv run reflex init'
    ]

# export backend
[phases.export]
    dependsOn = ['init']
    cmds = [
        'uv run reflex export --backend-only --no-zip'
    ]

# install caddy
[phases.caddy]
    dependsOn = ['export']
    nixPkgs = ['caddy']

# start
[start]
    cmd = 'uv run reflex run --backend-only --env prod'
