#!/bin/bash
echo "Test script starting..."
echo "Args: $@"
echo "Current directory: $(pwd)"
echo "Railway CLI available: $(which railway)"
echo "Railway auth status:"
railway whoami 2>&1 || echo "Not authenticated"
echo "Railway status:"
railway status 2>&1 || echo "No project linked"
echo "Env file exists: $(test -f .env && echo yes || echo no)"
echo "Env file contents (first 10 lines):"
head -10 .env 2>/dev/null || echo "Cannot read .env"
echo "Script completed."
